#!/bin/bash

export LD_LIBRARY_PATH=lib

if test "$1" == "tcp"
then
	./TestBed mclient 54.84.27.70 4950 tcp 1408 size 1024
elif test "$1" == "udt"
then
	./TestBed mclient 192.168.0.10 4950 udt 1408 size 32768
elif test "$1" == "utp"
then
	./TestBed mclient 192.168.0.10 4950 utp 1408 size 32768
elif test "$1" == "dccp"
then
	./TestBed mclient 192.168.0.10 4950 dccp 1408 size 32768
elif test "$1" == "udp"
then
	./TestBed mclient 192.168.0.10 4950 udp 1408 size 32768
elif test "$1" == "eudp"
then
	./TestBed mclient 192.168.0.10 4950 eudp 1408 size 32768
else
	echo "No such protocol"
fi
