#!/bin/bash

rm libtb.so.1.0
rm src/*.o

gcc -Wall -D_GNU_SOURCE -D_TB_LIBRARY -fPIC -c src/*.c -Iincludes \
-includeudt.h -includeutp.h `pkg-config --cflags glib-2.0` 

if [ $? == 0 ]
then 
	gcc -shared -Wl,-soname,libtb.so.1 -o libtb.so.1.0 *.o \
	 -Llib -ludt -lutp -pthread -lgdsl -laio `pkg-config --libs glib-2.0` 
else
	echo "gcc failure"
	exit -1
fi

if [ $? == 0 ]
then
	rm ~/share/Warp/Rafs/libtb.so.1.0
	rm ~/share/Warp/Rafs/doc -r
	cp libtb.so.1.0 ~/share/Warp/Rafs/
	chmod +r ~/share/Warp/Rafs/libtb.so.1.0
	doxygen Doxyfile
	cp -r doc ~/share/Warp/Rafs
	chmod +x ~/share/Warp/Rafs/doc
	chmod -R +r ~/share/Warp/Rafs/doc
	chmod +x ~/share/Warp/Rafs/doc/html
	chmod +x ~/share/Warp/Rafs/doc/html/search
	rm *.o
else
	echo "gcc failure"
	exit -1
fi
