#!/bin/bash

export LD_LIBRARY_PATH=lib/

if test "$1" == "tcp"
then
	./TestBed server 192.168.0.10 4950 tcp 8192
elif test "$1" == "udt"
then
	./TestBed mserver 192.168.0.10 4950 udt 8192
elif test "$1" == "utp"
then
	./TestBed mserver 192.168.0.10 4950 utp 8192
elif test "$1" == "dccp"
then
	./TestBed mserver 192.168.0.10 4950 dccp 8192
elif test "$1" == "udp"
then
	./TestBed mserver 192.168.0.10 4950 udp 8192
elif test "$1" == "eudp"
then
	./TestBed mserver 192.168.0.10 4950 udp 8192
else
	echo "No such protocol"
fi
	
