.TH "deprecated" 3 "Wed Feb 12 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.IP "\fBGlobal \fBtb_accept\fP (\fBtb_listener_t\fP *listener) __attribute__((always_inline)) __attribute__((deprecated))\fP" 1c
.IP "\fBGlobal \fBtb_accept\fP (\fBtb_listener_t\fP *listener) __attribute__((always_inline)) __attribute__((deprecated))\fP" 1c
.PP

