.TH "src/tb_common.c" 3 "Mon Feb 10 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tb_common.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tb_common\&.h'\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtb_print_address\fP (struct sockaddr_storage *store)"
.br
.ti -1c
.RI "char * \fBtb_get_address\fP (struct sockaddr_storage *store)"
.br
.ti -1c
.RI "\fBtb_time_t\fP * \fBtb_create_time\fP (clockid_t clk_id)"
.br
.RI "\fICreate a time struct\&. \fP"
.ti -1c
.RI "void \fBtb_destroy_time\fP (\fBtb_time_t\fP *time)"
.br
.RI "\fIDestroy a \fBtb_time_t\fP struct\&. \fP"
.ti -1c
.RI "void \fBtb_start_time\fP (\fBtb_time_t\fP *time)"
.br
.RI "\fIRecord the start time\&. \fP"
.ti -1c
.RI "void \fBtb_finish_time\fP (\fBtb_time_t\fP *time)"
.br
.RI "\fIRecord the finish time\&. \fP"
.ti -1c
.RI "void \fBtb_calculate_time\fP (\fBtb_time_t\fP *time)"
.br
.RI "\fICalculate the time difference between start and stop\&. \fP"
.ti -1c
.RI "char * \fBtb_create_test_file\fP (char *file_name, int *file_size)"
.br
.RI "\fILoad the file to be used for sending using the cilent\&. \fP"
.ti -1c
.RI "char * \fBtb_load_test_file\fP (char *file_name, int *file_size)"
.br
.RI "\fILoad file\&. \fP"
.ti -1c
.RI "char * \fBtb_load_random_file\fP (int size)"
.br
.RI "\fILoad random file of specified size\&. \fP"
.ti -1c
.RI "char * \fBtb_create_random\fP (char *path, int size)"
.br
.RI "\fICreate a random file\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void tb_calculate_time (\fBtb_time_t\fP *time)\fC [inline]\fP"

.PP
Calculate the time difference between start and stop\&. 
.PP
Definition at line 80 of file tb_common\&.c\&.
.SS "char* tb_create_random (char *path, intsize)"

.PP
Create a random file\&. 
.PP
Definition at line 182 of file tb_common\&.c\&.
.SS "char* tb_create_test_file (char *file_name, int *file_size)"

.PP
Load the file to be used for sending using the cilent\&. \fBParameters:\fP
.RS 4
\fIlistener\fP The listener to create the file for\&. 
.RE
.PP

.PP
Definition at line 89 of file tb_common\&.c\&.
.SS "\fBtb_time_t\fP* tb_create_time (clockid_tclk_id)"

.PP
Create a time struct\&. \fBParameters:\fP
.RS 4
\fIclk_id\fP The id of the type of clock to use\&. 
.RE
.PP

.PP
Definition at line 47 of file tb_common\&.c\&.
.SS "void tb_destroy_time (\fBtb_time_t\fP *time)"

.PP
Destroy a \fBtb_time_t\fP struct\&. 
.PP
Definition at line 59 of file tb_common\&.c\&.
.SS "void tb_finish_time (\fBtb_time_t\fP *time)\fC [inline]\fP"

.PP
Record the finish time\&. 
.PP
Definition at line 73 of file tb_common\&.c\&.
.SS "char* tb_get_address (struct sockaddr_storage *store)\fC [inline]\fP"

.PP
Definition at line 26 of file tb_common\&.c\&.
.SS "char* tb_load_random_file (intsize)"

.PP
Load random file of specified size\&. Loads a pre-generated file of the specified size, or generates it if it does not exist\&. 
.PP
Definition at line 148 of file tb_common\&.c\&.
.SS "char* tb_load_test_file (char *file_name, int *file_size)"

.PP
Load file\&. 
.PP
Definition at line 118 of file tb_common\&.c\&.
.SS "void tb_print_address (struct sockaddr_storage *store)\fC [inline]\fP"

.PP
Definition at line 18 of file tb_common\&.c\&.
.SS "void tb_start_time (\fBtb_time_t\fP *time)\fC [inline]\fP"

.PP
Record the start time\&. 
.PP
Definition at line 67 of file tb_common\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
