.TH "tb_e_data" 3 "Mon Feb 10 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tb_e_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tb_epoll\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file tb_epoll\&.h\&.
.SH "Field Documentation"
.PP 
.SS "void* data"

.PP
Definition at line 37 of file tb_epoll\&.h\&.
.SS "int fd"

.PP
Definition at line 36 of file tb_epoll\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
