.TH "src/tb_epoll.h" 3 "Mon Feb 10 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tb_epoll.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/epoll\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtb_epoll_t\fP"
.br
.ti -1c
.RI "struct \fBtb_e_data\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int(* \fBfunc_event\fP )(int events, void *data)"
.br
.RI "\fICallback for events on the socket\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBtb_epoll_t\fP * \fBtb_create_e_poll\fP (int sock_d, int max_events, int grp_events, void *data)"
.br
.ti -1c
.RI "void \fBtb_destroy_epoll\fP (\fBtb_epoll_t\fP *e_poll)"
.br
.ti -1c
.RI "int \fBtb_add_socket\fP (\fBtb_epoll_t\fP *e_poll, int sock_d)"
.br
.ti -1c
.RI "int \fBtb_poll_for_events\fP (\fBtb_epoll_t\fP *e_poll)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBevent_defaults\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int(* func_event)(int events, void *data)"

.PP
Callback for events on the socket\&. This function is called when an event occurs for the given fd\&. 
.PP
Definition at line 20 of file tb_epoll\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int tb_add_socket (\fBtb_epoll_t\fP *e_poll, intsock_d)"

.PP
Definition at line 76 of file tb_epoll\&.c\&.
.SS "\fBtb_epoll_t\fP* tb_create_e_poll (intsock_d, intmax_events, intgrp_events, void *data)"

.PP
Definition at line 19 of file tb_epoll\&.c\&.
.SS "void tb_destroy_epoll (\fBtb_epoll_t\fP *e_poll)"

.PP
Definition at line 68 of file tb_epoll\&.c\&.
.SS "int tb_poll_for_events (\fBtb_epoll_t\fP *e_poll)"

.PP
Definition at line 115 of file tb_epoll\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const int event_defaults"

.PP
Definition at line 41 of file tb_epoll\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
