.TH "tb_epoll_t" 3 "Wed Feb 12 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tb_epoll_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tb_epoll\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBe_id\fP"
.br
.ti -1c
.RI "int \fBw_time\fP"
.br
.ti -1c
.RI "int \fBmax_events\fP"
.br
.ti -1c
.RI "int \fBsock_d\fP"
.br
.ti -1c
.RI "struct epoll_event * \fBgrp_events\fP"
.br
.ti -1c
.RI "struct epoll_event * \fBevents\fP"
.br
.ti -1c
.RI "\fBfunc_event\fP \fBf_event\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file tb_epoll\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int e_id"

.PP
Definition at line 24 of file tb_epoll\&.h\&.
.SS "struct epoll_event* events"

.PP
Definition at line 29 of file tb_epoll\&.h\&.
.SS "\fBfunc_event\fP f_event"

.PP
Definition at line 30 of file tb_epoll\&.h\&.
.SS "struct epoll_event* grp_events"

.PP
Definition at line 28 of file tb_epoll\&.h\&.
.SS "int max_events"

.PP
Definition at line 26 of file tb_epoll\&.h\&.
.SS "int sock_d"

.PP
Definition at line 27 of file tb_epoll\&.h\&.
.SS "int w_time"

.PP
Definition at line 25 of file tb_epoll\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
