.TH "src/tb_endpoint.c" 3 "Mon Feb 10 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tb_endpoint.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tb_endpoint\&.h'\fP
.br
\fC#include 'tb_testbed\&.h'\fP
.br
\fC#include 'tb_protocol\&.h'\fP
.br
\fC#include 'tb_listener\&.h'\fP
.br
\fC#include 'tb_common\&.h'\fP
.br
\fC#include 'tb_udp\&.h'\fP
.br
\fC#include 'tb_utp\&.h'\fP
.br
\fC#include 'tb_udt\&.h'\fP
.br
\fC#include 'tb_stream\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBtb_client\fP (void *data)"
.br
.RI "\fIRuns the client\&. \fP"
.ti -1c
.RI "void * \fBtb_server\fP (void *data)"
.br
.RI "\fIRuns the server\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* tb_client (void *data)"

.PP
Runs the client\&. Runs the client, called from pthread_create\&.
.PP
\fBPrecondition:\fP
.RS 4
data must be of type \fBtb_listener_t\fP\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP Instance of \fBtb_listener_t\fP to run as client\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
As pthread_exit is called, this does not return\&. 
.RE
.PP

.PP
Definition at line 30 of file tb_endpoint\&.c\&.
.SS "void* tb_server (void *data)"

.PP
Runs the server\&. This starts a server instance, called from pthread_create\&.
.PP
\fBPrecondition:\fP
.RS 4
data must be of type \fBtb_listener_t\fP\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP This is an instance of \fBtb_listener_t\fP\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
As pthread_exit is called, this does not return\&. 
.RE
.PP

.PP
Definition at line 114 of file tb_endpoint\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
