.TH "tb_log_t" 3 "Wed Feb 12 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tb_log_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tb_logging\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "FILE * \fBfile\fP"
.br
.ti -1c
.RI "char * \fBfile_path\fP"
.br
.ti -1c
.RI "int \fBfile_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file tb_logging\&.h\&.
.SH "Field Documentation"
.PP 
.SS "FILE* file"

.PP
Definition at line 19 of file tb_logging\&.h\&.
.SS "int file_len"

.PP
Definition at line 21 of file tb_logging\&.h\&.
.SS "char* file_path"

.PP
Definition at line 20 of file tb_logging\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
