.TH "tb_options_t" 3 "Mon Feb 10 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tb_options_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tb_sock_opt\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPROTOCOL\fP \fBprotocol\fP"
.br
.RI "\fIThe protocol for these options\&. \fP"
.ti -1c
.RI "int \fBl4_r_b_size\fP"
.br
.RI "\fIThe size of the l4 read buffer\&. \fP"
.ti -1c
.RI "int \fBl4_s_b_size\fP"
.br
.RI "\fIThe size of the l4 write buffer\&. \fP"
.ti -1c
.RI "int \fBl3_r_b_size\fP"
.br
.RI "\fIThe size of the l3 read buffer\&. \fP"
.ti -1c
.RI "int \fBl3_s_b_size\fP"
.br
.RI "\fIThe size of the l3 write buffer\&. \fP"
.ti -1c
.RI "\fBCONGESTION_CONTROL\fP \fBcontrol\fP"
.br
.RI "\fIThe congestion control to use\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file tb_sock_opt\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBCONGESTION_CONTROL\fP control"

.PP
The congestion control to use\&. 
.PP
Definition at line 24 of file tb_sock_opt\&.h\&.
.SS "int l3_r_b_size"

.PP
The size of the l3 read buffer\&. 
.PP
Definition at line 22 of file tb_sock_opt\&.h\&.
.SS "int l3_s_b_size"

.PP
The size of the l3 write buffer\&. 
.PP
Definition at line 23 of file tb_sock_opt\&.h\&.
.SS "int l4_r_b_size"

.PP
The size of the l4 read buffer\&. 
.PP
Definition at line 20 of file tb_sock_opt\&.h\&.
.SS "int l4_s_b_size"

.PP
The size of the l4 write buffer\&. 
.PP
Definition at line 21 of file tb_sock_opt\&.h\&.
.SS "\fBPROTOCOL\fP protocol"

.PP
The protocol for these options\&. 
.PP
Definition at line 19 of file tb_sock_opt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
