.TH "tb_option_t" 3 "Tue Feb 4 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tb_option_t \- 
.PP
Contains option parameters for the protocol\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tb_sock_opt\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPROTOCOL\fP \fBprotocol\fP"
.br
.RI "\fIThe protocol to set options for\&. \fP"
.ti -1c
.RI "int \fBsend_buff_sz\fP"
.br
.ti -1c
.RI "int \fBrecv_buff_sz\fP"
.br
.ti -1c
.RI "int \fBprot_send_buff_sz\fP"
.br
.ti -1c
.RI "int \fBprot_recv_buff_sz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains option parameters for the protocol\&. 
.PP
Definition at line 17 of file tb_sock_opt\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int prot_recv_buff_sz"

.PP
Definition at line 24 of file tb_sock_opt\&.h\&.
.SS "int prot_send_buff_sz"

.PP
Definition at line 23 of file tb_sock_opt\&.h\&.
.SS "\fBPROTOCOL\fP protocol"

.PP
The protocol to set options for\&. 
.PP
Definition at line 19 of file tb_sock_opt\&.h\&.
.SS "int recv_buff_sz"

.PP
Definition at line 21 of file tb_sock_opt\&.h\&.
.SS "int send_buff_sz"

.PP
Definition at line 20 of file tb_sock_opt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
