.TH "tb_other_info" 3 "Mon Feb 10 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tb_other_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tb_listener\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBl_status\fP"
.br
.RI "\fIThe current status of the listener\&. \fP"
.ti -1c
.RI "int \fBsys_tid\fP"
.br
.RI "\fIThe tid of the thread according to the sys\&. \fP"
.ti -1c
.RI "int \fBcpu_affinity\fP"
.br
.RI "\fIThe current affinity of the cpu\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 216 of file tb_listener\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int cpu_affinity"

.PP
The current affinity of the cpu\&. 
.PP
Definition at line 220 of file tb_listener\&.h\&.
.SS "int l_status"

.PP
The current status of the listener\&. 
.PP
Definition at line 218 of file tb_listener\&.h\&.
.SS "int sys_tid"

.PP
The tid of the thread according to the sys\&. 
.PP
Definition at line 219 of file tb_listener\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
