.TH "src/tb_sock_opt.h" 3 "Wed Feb 12 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tb_sock_opt.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tb_protocol\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtb_options_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtb_set_sock_opt\fP (\fBtb_options_t\fP *options, int fd)"
.br
.RI "\fISet options for individual protocols\&. \fP"
.ti -1c
.RI "int \fBtb_set_bsd_sock_opts\fP (\fBtb_options_t\fP *options, int fd)"
.br
.RI "\fISet options for BSD sockets\&. Used by TCP, UDP and eUDP\&. \fP"
.ti -1c
.RI "int \fBtb_set_tcp_opts\fP (\fBtb_options_t\fP *options, int fd)"
.br
.RI "\fISet options for TCP\&. \fP"
.ti -1c
.RI "int \fBtb_set_udp_opts\fP (\fBtb_options_t\fP *options, int fd)"
.br
.RI "\fISet options for UDP\&. \fP"
.ti -1c
.RI "int \fBtb_set_udt_opts\fP (\fBtb_options_t\fP *options, int fd)"
.br
.RI "\fISet options for UDT\&. \fP"
.ti -1c
.RI "int \fBtb_set_audt_opts\fP (\fBtb_options_t\fP *options, int fd)"
.br
.RI "\fISet options for aUDT\&. \fP"
.ti -1c
.RI "int \fBtb_set_utp_opts\fP (\fBtb_options_t\fP *options, int fd)"
.br
.RI "\fISet options for uTP\&. \fP"
.ti -1c
.RI "int \fBtb_set_eudp_opts\fP (\fBtb_options_t\fP *options, int fd)"
.br
.RI "\fISet options for eUDP\&. \fP"
.ti -1c
.RI "int \fBtb_set_dccp_opts\fP (\fBtb_options_t\fP *options, int fd)"
.br
.RI "\fISet options for DCCP\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int tb_set_audt_opts (\fBtb_options_t\fP *options, intfd)"

.PP
Set options for aUDT\&. 
.PP
Definition at line 251 of file tb_sock_opt\&.c\&.
.SS "int tb_set_bsd_sock_opts (\fBtb_options_t\fP *options, intfd)"

.PP
Set options for BSD sockets\&. Used by TCP, UDP and eUDP\&. 
.PP
Definition at line 87 of file tb_sock_opt\&.c\&.
.SS "int tb_set_dccp_opts (\fBtb_options_t\fP *options, intfd)"

.PP
Set options for DCCP\&. 
.PP
Definition at line 294 of file tb_sock_opt\&.c\&.
.SS "int tb_set_eudp_opts (\fBtb_options_t\fP *options, intfd)"

.PP
Set options for eUDP\&. 
.PP
Definition at line 286 of file tb_sock_opt\&.c\&.
.SS "int tb_set_sock_opt (\fBtb_options_t\fP *options, intfd)"

.PP
Set options for individual protocols\&. This function is used to set the options on the currently used protocol\&.
.PP
\fBParameters:\fP
.RS 4
\fIlistener\fP The currently used listener\&.
.RE
.PP
\fBReturns:\fP
.RS 4
0 if options were set, -1 otherwise\&. 
.RE
.PP

.PP
Definition at line 43 of file tb_sock_opt\&.c\&.
.SS "int tb_set_tcp_opts (\fBtb_options_t\fP *options, intfd)"

.PP
Set options for TCP\&. 
.PP
Definition at line 133 of file tb_sock_opt\&.c\&.
.SS "int tb_set_udp_opts (\fBtb_options_t\fP *options, intfd)"

.PP
Set options for UDP\&. 
.PP
Definition at line 151 of file tb_sock_opt\&.c\&.
.SS "int tb_set_udt_opts (\fBtb_options_t\fP *options, intfd)"

.PP
Set options for UDT\&. 
.PP
Definition at line 171 of file tb_sock_opt\&.c\&.
.SS "int tb_set_utp_opts (\fBtb_options_t\fP *options, intfd)"

.PP
Set options for uTP\&. 
.PP
Definition at line 257 of file tb_sock_opt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
