.TH "tb_test_params_t" 3 "Mon Feb 10 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tb_test_params_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tb_listener\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBENDPOINT_TYPE\fP \fBtype\fP"
.br
.RI "\fIThe end point type\&. \fP"
.ti -1c
.RI "\fBPROTOCOL\fP \fBprotocol\fP"
.br
.RI "\fIThe protocol to test\&. \fP"
.ti -1c
.RI "\fBCONGESTION_CONTROL\fP \fBcontrol\fP"
.br
.RI "\fIThe congestion control algorithm to use\&. \fP"
.ti -1c
.RI "char * \fBaddress\fP"
.br
.RI "\fIThe address to bind/connect to\&. \fP"
.ti -1c
.RI "char * \fBport\fP"
.br
.RI "\fIThe port to bind/connect to\&. \fP"
.ti -1c
.RI "int \fBl4_r_b_size\fP"
.br
.RI "\fIThe size of the l4 read buffer\&. \fP"
.ti -1c
.RI "int \fBl4_w_b_size\fP"
.br
.RI "\fIThe size of the l4 write buffer\&. \fP"
.ti -1c
.RI "int \fBl3_r_b_size\fP"
.br
.RI "\fIThe size of the l3 read buffer\&. \fP"
.ti -1c
.RI "int \fBl3_w_b_size\fP"
.br
.RI "\fIThe size of the l3 write buffer\&. \fP"
.ti -1c
.RI "int \fBd_size\fP"
.br
.RI "\fIThe size of the data to send\&. \fP"
.ti -1c
.RI "char * \fBfile_name\fP"
.br
.RI "\fIThe name of the file to use\&. \fP"
.ti -1c
.RI "int \fBd_on_exit\fP"
.br
.RI "\fIDestroy the listener on exit\&. \fP"
.ti -1c
.RI "int \fBmonitor\fP"
.br
.RI "\fIMonitor the connection\&. \fP"
.ti -1c
.RI "int \fBprint_stats\fP"
.br
.RI "\fIPrint stats to screen\&. \fP"
.ti -1c
.RI "int \fBlog_enable\fP"
.br
.RI "\fIEnable logging\&. \fP"
.ti -1c
.RI "char * \fBlog_path\fP"
.br
.RI "\fIThe path to save the log to\&. \fP"
.ti -1c
.RI "int \fBpack_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file tb_listener\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* address"

.PP
The address to bind/connect to\&. 
.PP
Definition at line 85 of file tb_listener\&.h\&.
.SS "\fBCONGESTION_CONTROL\fP control"

.PP
The congestion control algorithm to use\&. 
.PP
Definition at line 82 of file tb_listener\&.h\&.
.SS "int d_on_exit"

.PP
Destroy the listener on exit\&. 
.PP
Definition at line 100 of file tb_listener\&.h\&.
.SS "int d_size"

.PP
The size of the data to send\&. 
.PP
Definition at line 96 of file tb_listener\&.h\&.
.SS "char* file_name"

.PP
The name of the file to use\&. 
.PP
Definition at line 97 of file tb_listener\&.h\&.
.SS "int l3_r_b_size"

.PP
The size of the l3 read buffer\&. 
.PP
Definition at line 92 of file tb_listener\&.h\&.
.SS "int l3_w_b_size"

.PP
The size of the l3 write buffer\&. 
.PP
Definition at line 93 of file tb_listener\&.h\&.
.SS "int l4_r_b_size"

.PP
The size of the l4 read buffer\&. 
.PP
Definition at line 89 of file tb_listener\&.h\&.
.SS "int l4_w_b_size"

.PP
The size of the l4 write buffer\&. 
.PP
Definition at line 90 of file tb_listener\&.h\&.
.SS "int log_enable"

.PP
Enable logging\&. 
.PP
Definition at line 107 of file tb_listener\&.h\&.
.SS "char* log_path"

.PP
The path to save the log to\&. 
.PP
Definition at line 108 of file tb_listener\&.h\&.
.SS "int monitor"

.PP
Monitor the connection\&. 
.PP
Definition at line 103 of file tb_listener\&.h\&.
.SS "int pack_size"

.PP
Definition at line 111 of file tb_listener\&.h\&.
.SS "char* port"

.PP
The port to bind/connect to\&. 
.PP
Definition at line 86 of file tb_listener\&.h\&.
.SS "int print_stats"

.PP
Print stats to screen\&. 
.PP
Definition at line 104 of file tb_listener\&.h\&.
.SS "\fBPROTOCOL\fP protocol"

.PP
The protocol to test\&. 
.PP
Definition at line 81 of file tb_listener\&.h\&.
.SS "\fBENDPOINT_TYPE\fP type"

.PP
The end point type\&. 
.PP
Definition at line 80 of file tb_listener\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
