.TH "tb_time_t" 3 "Mon Feb 10 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tb_time_t \- 
.PP
A struct to hold start, stop and elapsed times\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tb_common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "clockid_t \fBclk_id\fP"
.br
.ti -1c
.RI "struct timespec * \fBstart\fP"
.br
.ti -1c
.RI "struct timespec * \fBfinish\fP"
.br
.ti -1c
.RI "long long \fBn_sec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct to hold start, stop and elapsed times\&. 
.PP
Definition at line 51 of file tb_common\&.h\&.
.SH "Field Documentation"
.PP 
.SS "clockid_t clk_id"

.PP
Definition at line 53 of file tb_common\&.h\&.
.SS "struct timespec* finish"

.PP
Definition at line 55 of file tb_common\&.h\&.
.SS "long long n_sec"

.PP
Definition at line 57 of file tb_common\&.h\&.
.SS "struct timespec* start"

.PP
Definition at line 54 of file tb_common\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
