.TH "tb_utp_wrapper_t" 3 "Tue Jan 21 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tb_utp_wrapper_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tb_utp_wrapper\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct UTPSocket * \fBsocket\fP"
.br
.ti -1c
.RI "int \fBsock_fd\fP"
.br
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "char * \fBrec_buffer\fP"
.br
.ti -1c
.RI "int \fBread_bytes\fP"
.br
.ti -1c
.RI "int \fBwrite_bytes\fP"
.br
.ti -1c
.RI "int \fBbuffer_size\fP"
.br
.ti -1c
.RI "int \fBrec_buff_size\fP"
.br
.ti -1c
.RI "int \fBis_server\fP"
.br
.ti -1c
.RI "int \fBe_id\fP"
.br
.ti -1c
.RI "int \fBrecv_total\fP"
.br
.ti -1c
.RI "int \fBsent_total\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "\fBtb_listener_t\fP * \fBlistener\fP"
.br
.ti -1c
.RI "struct sockaddr_storage * \fBaddr_s\fP"
.br
.ti -1c
.RI "socklen_t \fBaddr_len\fP"
.br
.ti -1c
.RI "pthread_t * \fButp_thread\fP"
.br
.ti -1c
.RI "pthread_mutex_t * \fBlock\fP"
.br
.ti -1c
.RI "pthread_cond_t * \fBcond\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file tb_utp_wrapper\&.h\&.
.SH "Field Documentation"
.PP 
.SS "socklen_t addr_len"

.PP
Definition at line 38 of file tb_utp_wrapper\&.h\&.
.SS "struct sockaddr_storage* addr_s"

.PP
Definition at line 37 of file tb_utp_wrapper\&.h\&.
.SS "char* buffer"

.PP
Definition at line 25 of file tb_utp_wrapper\&.h\&.
.SS "int buffer_size"

.PP
Definition at line 29 of file tb_utp_wrapper\&.h\&.
.SS "pthread_cond_t* cond"

.PP
Definition at line 43 of file tb_utp_wrapper\&.h\&.
.SS "int e_id"

.PP
Definition at line 32 of file tb_utp_wrapper\&.h\&.
.SS "int is_server"

.PP
Definition at line 31 of file tb_utp_wrapper\&.h\&.
.SS "\fBtb_listener_t\fP* listener"

.PP
Definition at line 36 of file tb_utp_wrapper\&.h\&.
.SS "pthread_mutex_t* lock"

.PP
Definition at line 42 of file tb_utp_wrapper\&.h\&.
.SS "int read_bytes"

.PP
Definition at line 27 of file tb_utp_wrapper\&.h\&.
.SS "int rec_buff_size"

.PP
Definition at line 30 of file tb_utp_wrapper\&.h\&.
.SS "char* rec_buffer"

.PP
Definition at line 26 of file tb_utp_wrapper\&.h\&.
.SS "int recv_total"

.PP
Definition at line 33 of file tb_utp_wrapper\&.h\&.
.SS "int sent_total"

.PP
Definition at line 34 of file tb_utp_wrapper\&.h\&.
.SS "int sock_fd"

.PP
Definition at line 24 of file tb_utp_wrapper\&.h\&.
.SS "struct UTPSocket* socket"

.PP
Definition at line 23 of file tb_utp_wrapper\&.h\&.
.SS "int state"

.PP
Definition at line 35 of file tb_utp_wrapper\&.h\&.
.SS "pthread_t* utp_thread"

.PP
Definition at line 41 of file tb_utp_wrapper\&.h\&.
.SS "int write_bytes"

.PP
Definition at line 28 of file tb_utp_wrapper\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
