.TH "tb_udp_t" 3 "Fri Feb 7 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tb_udp_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tb_udp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsock_d\fP"
.br
.ti -1c
.RI "int \fBrecv_bytes\fP"
.br
.ti -1c
.RI "\fBtb_epoll_t\fP * \fBepoll\fP"
.br
.ti -1c
.RI "\fBtb_session_t\fP * \fBsession\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file tb_udp\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBtb_epoll_t\fP* epoll"

.PP
Definition at line 20 of file tb_udp\&.h\&.
.SS "int recv_bytes"

.PP
Definition at line 19 of file tb_udp\&.h\&.
.SS "\fBtb_session_t\fP* session"

.PP
Definition at line 21 of file tb_udp\&.h\&.
.SS "int sock_d"

.PP
Definition at line 18 of file tb_udp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
