.TH "src/tb_worker_pair.c" 3 "Wed Feb 12 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tb_worker_pair.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tb_worker_pair\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <gdsl\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBget_pair_key\fP (void *data)"
.br
.ti -1c
.RI "gdsl_element_t * \fBallocate_tuple\fP (void *data)"
.br
.ti -1c
.RI "void \fBfree_tuple\fP (gdsl_element_t *data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "gdsl_element_t* allocate_tuple (void *data)"

.PP
Definition at line 21 of file tb_worker_pair\&.c\&.
.SS "void free_tuple (gdsl_element_t *data)"

.PP
Definition at line 30 of file tb_worker_pair\&.c\&.
.SS "char* get_pair_key (void *data)"

.PP
Definition at line 14 of file tb_worker_pair\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
