.TH "worker_tuple" 3 "Tue Jan 14 2014" "Version 0.2" "TestBed" \" -*- nroff -*-
.ad l
.nh
.SH NAME
worker_tuple \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tb_worker_pair\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtb_worker_t\fP * \fBwork\fP"
.br
.ti -1c
.RI "\fBtb_session_t\fP * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file tb_worker_pair\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBtb_session_t\fP* data"

.PP
Definition at line 17 of file tb_worker_pair\&.h\&.
.SS "\fBtb_worker_t\fP* work"

.PP
Definition at line 16 of file tb_worker_pair\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TestBed from the source code\&.
