#!/bin/bash
gcc -Wall -D_GNU_SOURCE -o TestPerf \
-I../includes -includeutp.h -includeudt.h \  
perf_tests.c ../src/tb_protocol.c \
../src/tb_common.c ../src/tb_worker_pair.c \ 
../src/tb_worker_pair.c ../src/tb_worker.c \
../src/tb_logging.c -L../lib -lutp -ludt -lgdsl -lrt \
-pthread

